apiVersion: v1
kind: Service
metadata:
  name: no-aws-service
spec:
  selector:
    app: resource-montitoring
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-aws-deployment
spec:
  selector:
    matchLabels:
      app: resource-montitoring
  replicas: 4
  template:
    metadata:
      labels:
        app: resource-montitoring
    spec:
      containers:
      - name: resource-montitoring
        image: victoriaparkes/no-aws:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000